services:
  - type: web
    name: crawlvaani-backend
    env: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CHROME_PATH
        value: /opt/render/project/src/node_modules/puppeteer/.local-chromium/linux-1095492/chrome-linux/chrome
